### ISSUE TITLE
Gyro Missing On Betafpv Meteor 75 pro - STM32F411

### ISSUE THREAD

**Issue by Armalegend** [betaflight/unified-targets#1003]
My Gyro is missing after flashing 4.4.1.

Gyro: L3GD20

*** Support data submitted *** 
Id: "8a67b858-a587-404c-a6eb-e8fc3a57825c"

**Comment by haslinghuis** [comment]
Target used is STM32F411DISCOVERY.

Check table below which firmware needs to be used:


![image](https://user-images.githubusercontent.com/8344830/236675178-43d76b76-9ded-4852-8929-2b47655bf0fb.png)

**Comment by Armalegend** [comment]
Hi Mark, I tried this, but things go wrong in the betaflight configurator.The greying out I mean.Kind regards,PieterOn 07 May 2023 13:38, Mark Haslinghuis ***@***.***> wrote:
Target used is STM32F411DISCOVERY.
Check table below which firmware needs to be used:

**Comment by Armalegend** [comment]
I feel like a fool. Thank you for solving mate. It worked!
