### ISSUE TITLE
*** Support data submitted ***  Id: "9b58672c-92be-4560-a0df-d484e3780b0f"   # copy ID and provide to the betaflight team.

### ISSUE THREAD

**Issue by thyagorodriguesalvarez** [betaflight/unified-targets#1061]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by nerdCopter** [comment]
no description of the problem was provided whatsoever.  :man_shrugging: 
support id `9b58672c-92be-4560-a0df-d484e3780b0f` points to build key `73f543837229472b5690f4ca966bfdb7` which is not a core-build as required.
