### ISSUE TITLE
Rush Blade motor resources 5 and 6 flipped

### ISSUE THREAD

**Issue by Master92** [betaflight/unified-targets#1065]
Hello, I just got my hands on some `RUSH BLADE F722 mini analog` FCs and installed BF 4.4.2 with custom defaults on it.
On one FC, motor output 3 didn't work (that's a hardware issue), so I resoldered the respective wire to the pad labeled `M6`. When remapping resources in BF CLI

```
resource MOTOR 3 none
resource MOTOR 6 none
resource MOTOR 3 C06
save
```

It didn't seem to work at first, so I went ahead and tried to remap to another resource. What finally worked was mapping it to motor output M5 like so:

```
resource MOTOR 3 none
resource MOTOR 5 none
resource MOTOR 3 C07
save
```

I think, the configuration of the motor output resources in the unified-targets configuration is wrong and should be corrected in case somebody else might be able to reproduce this issue.

**Comment by nerdCopter** [comment]
i don't have an answer, but searched the defines and posting below for anyone interested.

Motor 1-6 definitions committed 3 yrs ago Oct 24 2020. motor 7,8 added Apr 25 2021

both `RUSH-BLADE_F7` & `_HD` defaults: 
```
resource MOTOR 1 C08  # pin C08: TIM8 CH3 (AF3) & DMA2 Stream 2 Channel 0
resource MOTOR 2 C09
resource MOTOR 3 B01  # pin B01: TIM3 CH4 (AF2) & DMA1 Stream 2 Channel 5
resource MOTOR 4 B00
resource MOTOR 5 C07  # pin C07: TIM8 CH2 (AF3) & DMA2 Stream 2 Channel 0
resource MOTOR 6 C06  # pin C06: TIM8 CH1 (AF3) & DMA2 Stream 2 Channel 0
resource MOTOR 7 B06
resource MOTOR 8 B07
```
https://github.com/betaflight/unified-targets/blob/master/configs/default/RUSH-BLADE_F7.config#L21

Unfortunate that schematics are rarely provided to public.
