### ISSUE TITLE
Id: "09133a2d-c57b-47b5-b2de-1196ba806e9f"

### ISSUE THREAD

**Issue by shrdin123** [betaflight/unified-targets#1104]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by nerdCopter** [comment]
no statement of what the problem is. :shrug:
