### ISSUE TITLE
Build server failure

### ISSUE THREAD

**Issue by GEME-Cyi** [betaflight/unified-targets#1120]
Betaflight Configurator can't build SOLOGOODF722 firmware

Build server failure: https://build.betaflight.com/api/builds/null/SOLOGOODF722 HTTP 404

**Comment by haslinghuis** [comment]
https://build.betaflight.com/api/builds/15a3983ea461149369490141626ecd2e/log

**Comment by GEME-Cyi** [comment]
Betaflight Configurator can't build 4.3.2

**Comment by haslinghuis** [comment]
@blckmn please check:

![image](https://github.com/betaflight/unified-targets/assets/8344830/fc965c01-ec62-49c5-8194-e55986c93fcf)

**Comment by blckmn** [comment]
4.3.2 uses generic targets.

**Comment by GEME-Cyi** [comment]
@blckmn How can I change it

**Comment by haslinghuis** [comment]
@blckmn @GEME-Cyi probably means 4.4.2 not available? Unified target has been added two days ago

![image](https://github.com/betaflight/unified-targets/assets/8344830/a1ff89a5-321a-4454-abb5-c37a4c040ebf)

**Comment by GEME-Cyi** [comment]
@haslinghuis Can a congfig error cause this?      #define UART3_RX_PIN B11

**Comment by blckmn** [comment]
Fixed. Just re-ran the action.
