### ISSUE TITLE
Gyro not detected on diatone mamba mk1 FURYF4OSD TARGET BETA 4.4.2

### ISSUE THREAD

**Issue by raider36** [betaflight/unified-targets#1127]
*** Datos de soporte enviados *** 
Id: "2bf8f54f-32c9-4e78-b6a7-f3853edb7694"

# copiar ID para proporcionar al equipo Betaflight.

**Comment by haslinghuis** [comment]
Please flash core only build and submit support ID to reveal the hardware used.
