### ISSUE TITLE
4.4.2 Gyro and Accelerometer not detected on Flywoo GOKU Versatile F411 1S 5A AIO ELRS

### ISSUE THREAD

**Issue by echinus** [betaflight/unified-targets#1138]
When flashing Betaflight 4.4.2 to a Flywoo GOKU Versatile F411 1S 5A AIO ELRS, no Gyro or Accelerometer is detected using the FLYWOOF411_5IN1_AIO target.  This is the board in a Flywoo Firefly 1S FR16 Nano Baby Quad V2.

*** Support data submitted *** 
Id: "51eef4b1-82e3-4c82-97f3-14289ffffcc3"

**Comment by haslinghuis** [comment]
Should be fixed in https://github.com/betaflight/unified-targets/pull/1137
