### ISSUE TITLE
support AT32 unified-targets 

### ISSUE THREAD

**Issue by lida2003** [betaflight/unified-targets#1158]
a) unified-targets are mostly STM series. 
b) And I have found there are AT32 support on [betaflight git repo](https://github.com/betaflight/betaflight/tree/master/src/main/target). 

So what I'm asking is when there will be AT32 unified-targets support?

**Comment by haslinghuis** [comment]
Firmware 4.5 will support AT32 configuration.

**Comment by lida2003** [comment]
Oh, I saw there is [configuration git in target](https://github.com/betaflight/config). 
So I wanna know support by adding target configuration in config git or here (unified target git)?

**Comment by haslinghuis** [comment]
Started documentation here: https://betaflight.com/docs/manufacturer/creating-configuration
