### ISSUE TITLE
SYNERGYF4 is missing Blackbox

### ISSUE THREAD

**Issue by leapole** [betaflight/unified-targets#1161]
### Describe the bug

SYNERGYF4 is missing Blackbox in 4.4.2

It was working in 4.3

### To Reproduce

Flash 4.4.2, Go to Blackbox tab,  Read error message

### Expected behavior

Blackbox is part of the firmware

### Support ID

```txt
Id: "d14af7c0-1b70-42bd-b803-b1d5d015dde3"
```

### Flight controller

SYNERGYF4

### Other components

TBS items

### Add any other context about the problem that you think might be relevant here

No Blackbox vars in the cli.

Its present in 4.3. 

There is a 16MB chip onboard

**Comment by nerdCopter** [comment]
@leapole , did you find the correct blackbox chip "custom define"? else we need a support-id from a core-build.
How to: https://hackmd.io/@nerdCopter/ByheaoLQh

**Comment by leapole** [comment]
its working in 4.5
