### ISSUE TITLE
GEP RC GEP-F722-35A AIO lost Gyro and possibly other ports after flashing BF fireware 4.40 and 4.4.2

### ISSUE THREAD

**Issue by upyopyo** [betaflight/unified-targets#1163]
### Describe the bug

Hi, I tried to flash BF fireware from the original version to 4.4.0 and 4.4.2  in order to use newer generation's GPS. And after flashing with sucessful update, Gyro is not detected anymore. (Sorry, I forgot the original BF version, possibly 4.2.x). Before flashing fireware, my drone is working fine.

At the beginning, the firmeware uploading was frozen at initializing step. Then I ran  ImpulseRC_Driver_Fixer.exe. Althoguh it finished with error message, now I can upload the BF firewares. Then I tried to flash with 4.4.0 and 4.4.2 and the both don't  detect Gyro. 

Next I found this link and a magic line for custom defines:
https://github.com/betaflight/betaflight/issues/12138
GYRO_SPI_MPU6000 ACC_SPI_MPU6000 

However, it still did not fix my Gyro detection, and now I have no idea how to fix this issue. 
Actually I found other issues. Airunit does not output video, and receiver does not receive signal although UARTs set properly as same as before flashing. Thus, I am thinking the problem is not only Gyro, but also other components, too. 

Maybe, I am missing very critical process. Please let me know how to fix all, thanks. 
These attached screenshots are after flashing frimewares. 

![gyro is gone after flashing fireware 4 4 v2](https://github.com/betaflight/betaflight/assets/78295605/61eeb7b2-9822-4a5b-a784-b98594a30975)
![gyro is gone after flashing 02](https://github.com/betaflight/betaflight/assets/78295605/fa08d8a2-773f-4434-8c87-622dedf42549)
![gyro is gone after flashing 03](https://github.com/betaflight/betaflight/assets/78295605/8b369fb0-7684-432c-b760-cfb42b492a29)
![gyro is gone after flashing 04](https://github.com/betaflight/betaflight/assets/78295605/3c44a8c0-3571-4a92-bde0-5f0d9a1c2d64)

### To Reproduce

rerun to flash fireware updatings.

### Expected behavior

I am expecting to see detect Gyro and 

### Support ID

```txt
*** Support data submitted *** 
Id: "2bf4e59c-4bdd-44d7-b9cc-cd98510d3235"
```

### Flight controller

GEP-F722-35A AIO

### Other components

receiver Futaba
VTX DJI airunit
GPS HGLRC M100_MINI GPS
buzzer gepRC superBuzzer

**Comment by nerdCopter** [comment]
10.9 has a bug that required "expert-mode" enabled. 
![image](https://github.com/betaflight/unified-targets/assets/56646290/db58b756-a2be-42f6-8358-6b0df5776a5c)

or you can use the 10.10-RC1 https://github.com/betaflight/betaflight-configurator/releases/tag/10.10.0-RC1

**Comment by upyopyo** [comment]
A
>>you will need firmware GEPRC_F722_AIO
Yes, I thought too, but there is no exact F722_AIO, and "_BT_" indicates a stack board item.  Mine is a just singal board.

B
>> For gyro all drivers are included in CORE build. 
umm, if you say so, , did I misstake a critical procedure after flashing firmware? At least, I hit  'connect' button' and selected 'apply custom Defaults' button. Then should it be all good, right? 

C
>>  10.9 has a bug that requires "expert-mode" enabled.
I tried to do the flash firmware 4.4.2 with 'Enable Expert Mode' ON, but it's the same story, not working. Do you imply to try development versions like pre-release?

additional questions to double check:
D
Do I need to install such Zadig and STM things? Because I can already do the flash Firmware in BF by USB connection, I don't need to do it, right? (Or this could be problem??)

E
There is no AIO version in the list of BF. Should I get a firmeware from official GEP RC website? (I don't think they have the one.)

![gyro is gone after flashing fireware 4 4 after reply01](https://github.com/betaflight/unified-targets/assets/78295605/29bfeeba-8c51-4c61-9e1f-db90bc6b1a89)
![gyro is gone after flashing fireware 4 4 after reply02](https://github.com/betaflight/unified-targets/assets/78295605/887fd09a-7010-44c6-a67d-518e14763587)
![gyro is gone after flashing fireware 4 4 after reply03](https://github.com/betaflight/unified-targets/assets/78295605/e28e582b-1c54-4722-8347-b15c6be92faa)

**Comment by nerdCopter** [comment]
you forgot the `GYRO_SPI_MPU6000 ACC_SPI_MPU6000` defines
![image](https://github.com/betaflight/unified-targets/assets/56646290/f2d499ea-902e-4d33-9023-f4faedb50988)

**Comment by upyopyo** [comment]
I tried the falshing with export mode and `GYRO_SPI_MPU6000 ACC_SPI_MPU6000`
However, it did not work. Critically Other UARTs also have not working neither since flashing. For instance, a receiver does not work although its power light is up. .


![gyro is gone after flashing fireware 4 4 after reply04](https://github.com/betaflight/unified-targets/assets/78295605/a76ca95b-122f-43a2-8a7e-496bb2813e6e)

**Comment by haslinghuis** [comment]
@blckmn please have a look.

 [GEPRCF_722_AIO](https://github.com/betaflight/unified-targets/blob/master/configs/default/GEPR-GEPRC_F722_AIO.config) is not available in cloud build. Same for [4.5 config](https://github.com/betaflight/config/tree/master/configs/GEPRC_F722_AIO)

**Comment by haslinghuis** [comment]
![image](https://github.com/betaflight/unified-targets/assets/8344830/b9f3828f-6452-492f-93b4-ee55354cd654)

**Comment by upyopyo** [comment]
Great, now All suncion are working, thank you so much!!!!

One last thing is about OSD's GPS satelites info. 
WTF cannot get satelite's numbers and home direction although Original OSD shows those values. I guess this issue is from new BF version 4.4. Can you fix this? or should I ask to WTF team? 


![OSD02 draw](https://github.com/betaflight/unified-targets/assets/78295605/52948eec-dbd7-49cc-8a32-89ebf0b3dab7)
![OSD draw](https://github.com/betaflight/unified-targets/assets/78295605/1e85a63c-a926-4ee7-972f-780b073aa71b)

**Comment by nerdCopter** [comment]
Discord for "support"; Github for bug-tracking.

**Comment by upyopyo** [comment]
for now, I got solution for my first question, then clsoing this ticket. Thanks for the supports!
