### ISSUE TITLE
f4 1-2s no gyro

### ISSUE THREAD

**Issue by budgieda** [betaflight/unified-targets#1165]
### Describe the bug

Id: "06a0f8cf-b167-421b-913c-fea65f69feee"

### To Reproduce

Id: "06a0f8cf-b167-421b-913c-fea65f69feee

### Expected behavior

Id: "06a0f8cf-b167-421b-913c-fea65f69feee

### Support ID

```txt
Id: "06a0f8cf-b167-421b-913c-fea65f69feee"
```

### Flight controller

lite radio 2se

**Comment by budgieda** [comment]
where to find the CLI for this model and the board firmware?  thx

**Comment by haslinghuis** [comment]
You did not provide any info about brand or board. Please provide a product link from the manufacturer / web store.

**Comment by budgieda** [comment]
Betafpv f4 aio 1s frsky fcc

**Comment by haslinghuis** [comment]
Probably needs BETAFPVF411RX

**Comment by budgieda** [comment]
I found the cli and it is throwing me errors in the console in red.

**Comment by nerdCopter** [comment]
anything 4.3 and prior upgraded to 4.4 and later will have different naming for some parameters or lack of parameters if a feature was not selected in the cloud-build options.  
Discord for support, Github for bugs.  -- this is a support issue, not a bug.
https://hackmd.io/@nerdCopter/ByheaoLQh
