### ISSUE TITLE
Change the weblink in manufacturers list

### ISSUE THREAD

**Issue by jhemcu** [betaflight/unified-targets#1178]
In the past time we have built a website belonging to our brand so would like to replace the website link in the list of manufacturers.

`|JHEF|JHE\_FPV|https://github.com/atgfpeyv|`

[[www.jhemcu.com](www.jhemcu.com)](https://www.jhemcu.com/)

**Comment by nerdCopter** [comment]
https://github.com/betaflight/unified-targets/pull/1180
https://github.com/betaflight/config/pull/206
