### ISSUE TITLE
About  line endings

### ISSUE THREAD

**Issue by tobeornottobe81** [betaflight/unified-targets#1195]
![image](https://github.com/betaflight/unified-targets/assets/57481312/9b5ee9a7-5fad-410b-a602-2542b0efe339)

The flight control configuration file I uploaded encountered an error regarding line endings during detection, as follows

ERROR: file xxx has got invalid (DOS) line endings

**Comment by nerdCopter** [comment]
is it a file you created, or is it a file in our repo?

**Comment by tobeornottobe81** [comment]
This file was created by ourselves, and after being encrypted and decrypted by IPguard, it becomes like this. thank you.
