### ISSUE TITLE
Betaflight-configurator can't build DREAMFLYF411 firmware

### ISSUE THREAD

**Issue by GEME-Cyi** [betaflight/unified-targets#1219]
Build server failure: https://build.betaflight.com/api/builds/0/DREAMFLYF411 HTTP 404

**Comment by haslinghuis** [comment]
@blckmn please check as this target only shows for 4.5

![image](https://github.com/betaflight/unified-targets/assets/8344830/dbd524b1-bd92-4924-a7e7-c8c54b2434a1)

**Comment by nerdCopter** [comment]
still needs attention
![image](https://github.com/betaflight/unified-targets/assets/56646290/498a3682-91a3-4d65-9284-934bdbe47356)
