### ISSUE TITLE
TinyApe Flight Controller (BETAFPVF4SX1280) Missing Gyro after BetaFlight 4.4

### ISSUE THREAD

**Issue by spla9t-lab** [betaflight/unified-targets#1250]
After updating to Betaflight 4.4 on the TinyApe (MCU: STM32F411CEU6 - Firmware target BETAFPVF4SX1280) the gyro is missing due to a mismatched gyro in the cloud configuration.

This can be reproduced by updating the DarwinFPV TinyApe from Betaflight 4.3 to Betaflight 4.4 and attempting to reconnect the flight controller (MCU: STM32F411CEU6 - Firmware target BETAFPVF4SX1280).

This was submitted with the Support ID: 769acffa-228d-47fb-8dbd-2240123c6033

Thanks for everything you do!

**Comment by haslinghuis** [comment]
Darwin needs it's own configuration file instead of using another manufacturers work.

**Comment by ot0tot** [comment]
There is already a corrected target for the Darwin FC:
https://github.com/betaflight/unified-targets/blob/master/configs/default/DAFP-DARWINF4SX1280HD.config
