### ISSUE TITLE
Missing gyro after firmware update to BF 4.4,3

### ISSUE THREAD

**Issue by scottst** [betaflight/unified-targets#1254]
I am working on the Hobbywing XRotor F722 3-6S 20x20 Stack/Combo (F7 FC / 32Bit 45A 4in1 ESC)

I grabbed the support data from the CLI for this id:
Id: "3ecc1f4d-81b0-4443-b0bf-49a2b4c6a384"

The documentation for the stack said to flash with the target Flywoof7dual which is what i used. Then i get an error for no gyro detected.

MCU: STM32F722
Gyro: MPU6500
Barometer: No
OSD: Yes
Blackbox: Onboard
UARTS: 4 Sets
ESC Software: DShot300/600/12000
ESC Telemetry: Yes
Led Controller: Yes
Input Voltage: 3-6s Lipo (12.6-25.2V)
BEC: 5V 2A / 10V 2A
Mounting Pattern: 20x20mm M3 / 30x30mm M3

Please help!

**Comment by haslinghuis** [comment]
Should you not be using https://github.com/betaflight/unified-targets/blob/master/configs/default/HOWI-HOBBYWING_XROTORF7CONV.config instead
