### ISSUE TITLE
Matek F405 Target (for NamelessRC Super AIO FC+ESC+DVR F4 15A 720p 1S) reports no gyro after update to 4.4.3

### ISSUE THREAD

**Issue by jeaton2411** [betaflight/unified-targets#1282]
Core only restored the Gyro here is the support data code: 4b0e7a30-78f6-4c43-b12c-627798910789

Thanks ahead of time.

**Comment by nerdCopter** [comment]
Please use 10.10-RC3 or nightly Configurator and add `GYRO_SPI_MPU6000 ACC_SPI_MPU6000` to the `Custom Defines` field.
I do not see a target specific to the NamelessRC **clone**. and i presume Betaflight will not add MPU6000 to the **branded** Matek405mini target.
