### ISSUE TITLE
I am new so I don’t know how to download butterfly configuration. I need help with that.

### ISSUE THREAD

**Issue by MehalAlamim** [betaflight/unified-targets#1327]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by KarateBrot** [comment]
You can go here for the releases: https://github.com/betaflight/betaflight-configurator/releases

Or for the browser version just go to: https://app.betaflight.com/

**Comment by haslinghuis** [comment]
We cannot help with butterfly as this is Betaflight.

Otherwise please use [discord](https://discord.com/invite/gV4XSq3fus) for further Betaflight support
