### ISSUE TITLE
the gyro not working after flash

### ISSUE THREAD

**Issue by Alex-spec-code** [betaflight/unified-targets#1333]
*** Support data submitted *** 
Id: "902e83eb-d5bc-4469-8adb-b59308ba0655"

**Comment by haslinghuis** [comment]
If `darwin` use `DARWINF411`
If `eachine` add `ACC_SPI_ICM20689 GYRO_SPI_ICM20689` in custom defines while flashing.

**Comment by haslinghuis** [comment]
See also:

- https://github.com/betaflight/unified-targets/issues/1274
- https://github.com/betaflight/unified-targets/issues/1119
