### ISSUE TITLE
Barometer not working on Pavo20 after flashing to 4.5

### ISSUE THREAD

**Issue by BrendanTipney** [betaflight/unified-targets#1334]
Barometer not working on Pavo20 after flashing to 4.5. Flashed it back to core to get this info dump.

FC: F4 2-3S 20A AIO FC V1

Data ID: 1139f7af-3d90-48fa-b926-1a0cc3523312

**Comment by haslinghuis** [comment]
Should be fixed in https://github.com/betaflight/config/pull/481 as 4.5 does not use unified-targets repo. Might need to force a new build by removing or adding an option.

**Comment by BrendanTipney** [comment]
Wow, You are fast. Sorry I didn't search that. Will check it out. Thanks!

**Comment by BrendanTipney** [comment]
That fixed it. Thanks for your response and efforts on this amazing software 🙏
