### ISSUE TITLE
gyro locked 4.5.1 MPU6500

### ISSUE THREAD

**Issue by gOttifpv** [betaflight/unified-targets#1339]
Diatone mamba dji f7222 mk2 128 bit MPU6500

Flashed 4.5.1 from 4.5.0 and gyro is locked. Tried flashing back to 4.5.0 still locked so I thought I had a bad gyro, but decided to try earlier version 4.3.2 and gyro works, so I'm thing the target in the new software isn't compatible, how can I fix this. Thank you.....

**Comment by haslinghuis** [comment]
Seems this board is using `MAMBAF722_I2C` config.

**Comment by gOttifpv** [comment]
Just flashed board with MAMBAF22_12C and was successful and gyro detected, when I did auto detect it recommended the MAMBAF22. Thank you I appreciate your help...
