### ISSUE TITLE
No gyro/acc detected after updating Stable F411 FC to BF 4.5

### ISSUE THREAD

**Issue by willrawls** [betaflight/unified-targets#1345]
BF CLI Id: "39f33bd2-bfce-4fc5-bb71-61e56f235328"

Works fine on BF 4.3 but no gyro/acc is detected on BF 4.4 and up.

Firmware Target: MATEKF411

Link to FC manual (https://www.geprc.com/download/en/GEPRC-GEP-STABLE-F411-Manual-EN-V1_0.pdf)

**Comment by haslinghuis** [comment]
Links shows it is using MPU6000 which is in the target already. Flash with Core Only and provide a support ID again.
Suspect `GYRO_SPI_ICM20602 ACC_SPI_ICM20602` in custom defines while flashing would work.

**Comment by willrawls** [comment]
Core only bf 4.5 CLI Id: "4a2c24be-4062-4aae-8f76-bf29a32bba41"

**Comment by haslinghuis** [comment]
Hmm, still does not show up gyro / acc. 
Flash working 4.3x and submit support ID to see if we can find any difference

**Comment by willrawls** [comment]
BF 4.3.2 with working gyro/acc support Id: "b4733470-596d-46b6-90f1-600f68c58308"

**Comment by haslinghuis** [comment]
Hmmm, GYRO=ICM42688P, ACC=ICM42688P

Add `GYRO_SPI_ICM42688 ACC_SPI_ICM42688` to custom defines while flashing

**Comment by willrawls** [comment]
That worked, will do test flight. Thank you for your help!

**Comment by ot0tot** [comment]
What happens if you flash the correct target? 😆 
You should be flashing `GEPRCF411`.
