### ISSUE TITLE
No Gyro / Acc found after firmware update from 4.4.3 to 4.5.1

### ISSUE THREAD

**Issue by JureMedo** [betaflight/unified-targets#1354]
Hello.
After I flash firmware  from 4.4.3 BTFL to 4.5.1 (full chip erase) ... a warning of 'no Gyro/ Acc  found' is showing

After Auto-detect button ---> 
Target: BETAFLIGHT4
Firmware: 4.5.1

FC board: CruxF405 HD ELRS from Happymodel

*** Support data submitted *** 
Id: "20a43d0f-d113-45cc-8709-7cc225229d83"
Id: "ad83bd40-5ec1-4211-917d-42a400b1b79b"

Also I revert it back to 4.4.3 but the issue stais the same ... 'no Gyro' 
Before the change

Thanks

**Comment by nerdCopter** [comment]
Clone of `BETAFLIGHTF4` should not use this target.
Maybe the correct target is `CRAZYBEEF405`.
https://hackmd.io/@nerdCopter/ByheaoLQh
