### ISSUE TITLE
New ID for FLYTEX LTD

### ISSUE THREAD

**Issue by MatviiG** [betaflight/unified-targets#1356]
Hi, 

could you please add an ID for FLYTEX LTD
website: https://www.flytex.pro/
Targets: FLYTEX405 ; FLYTEX722

BR, 
Matvii

**Comment by haslinghuis** [comment]
@MatviiG we moved on to another [repo](https://github.com/betaflight/config)

Please check https://betaflight.com/docs/development/manufacturer/requirements-for-submission-of-targets
