### ISSUE TITLE
Manufacturer ID for GEPRC

### ISSUE THREAD

**Issue by Linjieqiang** [betaflight/unified-targets#149]
As per https://github.com/betaflight/betaflight/blob/master/docs/TargetMaintenance/CreatingAUnifiedTarget.md, please assign manufacturer ID for GEPRC.

Requested Id : GEPR
Name : GEPRC
URL : https://geprc.com/

**Comment by mikeller** [comment]
@Linjieqiang: See #149. I've also added you as the target maintainer for GEPRC. Let me know if this should be changed to somebody else.

**Comment by Linjieqiang** [comment]
Thanks @mikeller . I am the target maintainer for GEPRC. I will actually do the maintenance of the GEPRC's hardware board.
