### ISSUE TITLE
Manufacturer ID for FOSS

### ISSUE THREAD

**Issue by cvetaevvitaliy** [betaflight/unified-targets#223]
Manufacturer ID for FOSS
Requested Id : FOSS
Name : FOSS
URL : none

**Comment by cvetaevvitaliy** [comment]
Manufacturer ID for FOSS
Requested Id : FOSS
Name : FOSS
URL : none

**Comment by etracer65** [comment]
Manufacturer id already exists. Please read: 

https://github.com/betaflight/unified-targets/blob/master/Manufacturers.md

**Comment by cvetaevvitaliy** [comment]
@etracer65  I ask this lssues 
<img width="936" alt="Снимок экрана 2020-03-21 в 16 58 15" src="https://user-images.githubusercontent.com/26421560/77229226-462ee900-6b95-11ea-9c3f-a8a1175fa9d9.png">

**Comment by Asizon** [comment]
lol but is foss your brand name @cvetaevvitaliy ?

**Comment by mikeller** [comment]
@Asizon: Manufacturer ids are not only assigned for brands, have a look at https://github.com/betaflight/unified-targets/blob/master/Manufacturers.md.
