### ISSUE TITLE
add a new manufacturer-ID for GEPRC

### ISSUE THREAD

**Issue by wwwgeprccom** [betaflight/unified-targets#263]
Hello, we would like to add a new manufacturer-ID: GEPRC
in betaflight Configurator
Our website is www.geprc.com
My email is: 326717324@qq.com
Thank you!

**Comment by mikeller** [comment]
@wwwgeprccom: GEPRC is already registered under the id GEPR, with @Linjieqiang registered as the maintainer. Are you the new maintainer.

**Comment by wwwgeprccom** [comment]
Hi Mikeller,
Yes, now the new projects are in charged by me, as there is already GEPR registered there, so I think I just need to upload new projects to BF with our GEPR id, right? Thanks. I will withdraw my request.
