### ISSUE TITLE
add a new manufacturer-ID: LNRC

### ISSUE THREAD

**Issue by lan-rc2020** [betaflight/unified-targets#336]
Hello, we would like to add a new manufacturer-ID: LANR
in betaflight Configurator
Our website is   www.lan-rc.com
My email is: 2423847452@qq.com
Thank you!

**Comment by mikeller** [comment]
We are neither a partner of you, nor were you ever given the permission to use our name and logo on your page. Please fix this before you re-apply for registration as a manufacturer.
