### ISSUE TITLE
Request for new manufacturer ID

### ISSUE THREAD

**Issue by mStrangers** [betaflight/unified-targets#342]
Hi ,
i'm requesting a new manufacturer id for the unified target database: 
Manufacturer ID : DFPV
Company name : Drone-Fpv-Racer
Website URL : https://www.drone-fpv-racer.com

**Comment by mikeller** [comment]
@mStrangers: See #342. Am I right to assume that you will be the maintainer for this manufacturer's targets?

**Comment by mStrangers** [comment]
yes i'll be the maintainer for this manufacturer's targets
