### ISSUE TITLE
Add a new manufacturer id for the unified target database

### ISSUE THREAD

**Issue by lan-rc2020** [betaflight/unified-targets#344]
Hello
i'm requesting a new manufacturer id for the unified target database
Manufacturer ID :LANR
Company name :LAN-RC
Our website is www.lan-rc.com
My email is: 2423847452@qq.com
Thank you!

**Comment by mikeller** [comment]
Duplucate of #336.

**Comment by lan-rc2020** [comment]
However, my&nbsp;manufacturer ID&nbsp;has not been added successfully. What should I do?








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/unified-targets"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 下午2:36
收件人:&nbsp;"betaflight/unified-targets"<unified-targets@noreply.github.com&gt;;
抄送:&nbsp;"andy"<2423847452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [betaflight/unified-targets] Add a new manufacturer id for the unified target database (#344)





 
Closed #344.

**Comment by mikeller** [comment]
@lan-rc2020: Why did you close your originia issue then? If you close it the assumption is that you are no longer interested. If you are still interested then reopen it and wait for it to be worked on.

**Comment by lan-rc2020** [comment]
My&nbsp;&nbsp;issue&nbsp;was opened 12 days ago, but it was not approved, so I thought there was something wrong with it. Yesterday my boss asked me to change my ID number from LNRC to LANR, so I reapplied. I just saw your email, I reopened the request, thank you!










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/unified-targets"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上7:48
收件人:&nbsp;"betaflight/unified-targets"<unified-targets@noreply.github.com&gt;;
抄送:&nbsp;"andy"<2423847452@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [betaflight/unified-targets] Add a new manufacturer id for the unified target database (#344)





 
@lan-rc2020: Why did you close your originia issue then? If you close it the assumption is that you are no longer interested. If you are still interested then reopen it and wait for it to be worked on.

**Comment by lan-rc2020** [comment]
&nbsp;hello&nbsp;Michael:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Can you help me register the manufacturer ID as soon as possible,I have been waiting for half a month.&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Thank you very much.我
经等了有半个月了，非常感谢







&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael Keller"<notifications@github.com&gt;; 
发送时间: 2020年9月1日(星期二) 晚上7:48
收件人: "betaflight/unified-targets"<unified-targets@noreply.github.com&gt;; 
抄送: "andy"<2423847452@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [betaflight/unified-targets] Add a new manufacturer id for the unified target database (#344)





 
@lan-rc2020: Why did you close your originia issue then? If you close it the assumption is that you are no longer interested. If you are still interested then reopen it and wait for it to be worked on.
