### ISSUE TITLE
Manufacturer ID for FPVR

### ISSUE THREAD

**Issue by marvel59** [betaflight/unified-targets#351]
Hello, we would like to add a new manufacturer-ID: FPVR in betaflight Configurator

Our website is http://fpvracer.cn/
My email is: 370724104@qq.com
Requested Id : FPVR
Name : FPVRACER

Thank you!

**Comment by mikeller** [comment]
There does not seem to be any links to products or support for these products on your website - can you please supply the correct link where this can be found?

**Comment by marvel59** [comment]
Our website is under construction and will be completed in about a week, the link is correct.

**Comment by mikeller** [comment]
@marvel59: Thanks, we will add the manufacturer id when the website is complete.
