### ISSUE TITLE
Request manufacturer ID for nvisionfpv

### ISSUE THREAD

**Issue by hongzhou-zeng** [betaflight/unified-targets#377]
Hello, we would like to add a new manufacturer-ID for nvisionfpv
Company name: : nvisionfpv
url:http://nvisionfpv.com/
Thank you!

**Comment by hongzhou-zeng** [comment]
Hello, we would like to add a new manufacturer-ID for nvisionfpv
Company name: : nvisionfpv
url:http://nvisionfpv.com/
Thank you

**Comment by mikeller** [comment]
Added in #378.
