### ISSUE TITLE
HIFIONRC target does not work for HIFIONRC AIO F7 Flight Controller OSD 

### ISSUE THREAD

**Issue by fuleinist** [betaflight/unified-targets#385]
HIFIONRC target does not work for HIFIONRC AIO F7 Flight Controller OSD 
product https://www.banggood.com/HIFIONRC-AIO-F7-Flight-Controller-OSD-Built-in-25A-Blheli_S-2-6S-4-In-1-Brushless-ESC-25_5x25_5mm-for-Toothpick-FPV-Racing-Drone-p-1716227.html

config used https://raw.githubusercontent.com/betaflight/unified-targets/master/configs/default/HFOR-HIFIONRCF7.config

No gyro nor motor config upon full reset

**Comment by etracer65** [comment]
The target you reference does not appear to be for the board you linked to. The target is set up for a dual-gyro board which seems to be a different HIFIONRC flight controller. Suggest you contact the manufacturer to get details about which target should be used for your board.
