### ISSUE TITLE
Apply new manufacturer ID for NIDICI 

### ISSUE THREAD

**Issue by WilsonChang** [betaflight/unified-targets#421]
Hello Administrator, 

Apply assigning a new manufacturer ID for the following FPV manufacturer:  
Manufacturer name: 
Huizhou NIDICI Electronic Co., LTD
Contact:
www.nidici.com
 
About NIDICI：
Thank you for visiting NIDICI FPV!  Our goal is to provide the latest & greatest FPV equipment & support.

**Comment by mikeller** [comment]
@WilsonChang: See https://github.com/betaflight/unified-targets/pull/425. Am I correct to assume that you will be the target maintainer for this manufacturer?

**Comment by WilsonChang** [comment]
@mikeller OK,  and thank you!
