### ISSUE TITLE
Add new manufacturer ID for HOMFPV

### ISSUE THREAD

**Issue by flosean** [betaflight/unified-targets#427]
Apply assigning a new manufacturer ID for the following FPV manufacturer:
Manufacturer name : HOMFPV
Contact : support@homfpv.com
Website : www.homfpv.com
ID : HOMS

Thanks

**Comment by mikeller** [comment]
@flosean: Sorry, I did not have time to look at this until now - is this still needed?

**Comment by flosean** [comment]
Hi Mikeller, it doesn't need the ID anymore, thanks😄
