### ISSUE TITLE
FOXE-FOXEERF722V2.config config file error

### ISSUE THREAD

**Issue by Johnsnow-foxeer** [betaflight/unified-targets#480]
### Describe the bug
Can not find the Uart, cannot setup parameters

### To Reproduce
Flash any BF since 4.1.0 to FOXEER F722 V2 and apply custom defaults, then change motor protocol to any dshot.

### Expected behavior
Configurator can connect to FC with any dshot and can see voltage.

### Flight controller configuration

# dma

Correct
dma ADC 3 0

ERROR 
dma ADC 3 1

### Setup / Versions
 
 - Flight controller: 
 
 - Other components:
 
 - How are the different components wired up:

**Comment by mikeller** [comment]
@SteveCEvans: Looks like another target where the ADC change leads to a lockup.
