### ISSUE TITLE
SkystarsF405 has a wrong baro CSB pin config

### ISSUE THREAD

**Issue by DusKing1** [betaflight/unified-targets#502]
https://github.com/betaflight/unified-targets/commit/cadb4d7f1da023eb4f796e8969e205eb897abd26#commitcomment

**Comment by msfujino** [comment]
I asked Skystars support, and I got the following answer.

    You may have an older VERSION of FC that does not support Baro. Baro affects DFU mode.
    It's a hardware problem, not a software problem.
    The new version now uses Baro.

Even if an older versions of FC, both DFU and Baro will work properly with a pull-down resistor as shown above.
