### ISSUE TITLE
Add CC-Pin to Flywoo Goku V2.1 definition

### ISSUE THREAD

**Issue by cad435** [betaflight/unified-targets#518]
### Is your feature request related to a problem? Please describe.
Flywoo Goku V2.1 is used in the LR4 Explorer selled on Banggood Banggood Link. I assume this is the actual product from Flywoo.

CC Pin is broken out and clearly marked on silkscreen. However Flywoo decided or forgot to define it in the hardware file (**FLWO-FLYWOOF411V2.config**).
Flywoo GOKU F411

### Describe the solution you'd like
I reached out to Flywoo and actaully got an answer. CC-Pin is connected to B04. With this information I got it working just fine.

![image](https://user-images.githubusercontent.com/16453385/137585288-4e41fd75-b55c-476d-a357-a3fca51146b5.png)

Maybe it should get added to the default config if its already there in hardware...

### Describe alternatives you've considered
Adding it manually everytime someone decided to want CC on a Guko-FC. Problem is: You can't seem to find the pinout for this particular FC and this particular pin anywhere on the internet, so if Flywoo didn't decide to respond on my mail I would have to completely disassemble the quad and manually track the trace (possible, but not a labour which should be done by different individuals over and over again imo)...

Have a nice day,
- cad435

**Comment by DusKing1** [comment]
@flywoo
