### ISSUE TITLE
HGLRC Zeus 722 hangs after applying config.

### ISSUE THREAD

**Issue by obeny** [betaflight/unified-targets#523]
Description:
HGLRC Zeus F722 hangs after power on.

How to reproduce:
Flash latest 4.3 development BF, apply custom defaults when asked.
Board is non-responsive, switching tabs in configurator is not possible.

This problem affects only Zeus F722 FCs only.

For details see:
https://github.com/betaflight/betaflight/issues/11026

**Comment by HGLRC-D** [comment]
Do not! This will make the BMP280 on the target not work properly.

**Comment by jessearmand** [comment]
Hi @obeny and @HGLRC-D this default configuration is not right, I'm using firmware version 4.2.10, and I had to change the `baro_bustype` into SPI. That's how it was configured before this unified target changes.

Here's what I set to enable the barometer again:
````
set baro_bustype = SPI
set baro_spi_device = 1
set baro_i2c_device = 0
````

**Comment by jessearmand** [comment]
@HGLRC-D As I mentioned elsewhere, I noticed that this config was created without `baro_bustype` being set to any value. 

As can be seen here in [barometer.c](https://github.com/betaflight/betaflight/blob/18af30321dc6ba352f44125fd923f359560a8e5a/src/main/sensors/barometer.c#L155-L273) not having a value there could potentially cause problems. 

But, I haven't tested on the latest 4.3, could you please verify that the BMP280 should work normally with SPI?

**Comment by alienwaredream** [comment]
> Do not! This will make the BMP280 on the target not work properly.

所以在BF4.3下化骨龙F722飞控到底能不能启用气压计呢？

**Comment by HGLRC-D** [comment]
> > 不要！这将使目标上的 BMP280 无法正常工作。
> 
> 所以在BF4.3下化骨龙F722飞控到底能不能启用气压计呢？

可以用的

**Comment by DusKing1** [comment]
English please?

**Comment by alienwaredream** [comment]
> > > 不要！这将使目标上的 BMP280 无法正常工作。
> > 
> > 
> > 所以在BF4.3下化骨龙F722飞控到底能不能启用气压计呢？
> 
> 可以用的

我试了在4.2下用

**Comment by HGLRC-D** [comment]
I tested 4.3 here and there is no problem. Have you tried to re-burn the firmware?

> English please?

Sorry, i will pay attention.

**Comment by HGLRC-D** [comment]
> > > > 不要！这将使目标上的 BMP280 无法正常工作。
> > > 
> > > 
> > > 所以在BF4.3下化骨龙F722飞控到底能不能启用气压计呢？
> > 
> > 
> > 可以用的
> 
> 我试了在4.2下用 set baro_bustype = SPI set baro_spi_device = 1 可以正常启用气压计
> 
> 但是在4.3下，只要一输入set baro_bustype = SPI 保存之后飞控重启就死机了，是不是和4.3对SPI总线定义有冲突？

Have you tried boot?
Confirm "set baro_bustype = SPI
set baro_spi_device = 1" Complete input?
I tested 4.30 , and baro can be used normally.
If the attempt fails, I will ask my colleague to contact you.

**Comment by HGLRC-D** [comment]
> > > > 不要！这将使目标上的 BMP280 无法正常工作。
> > > 
> > > 
> > > 所以在BF4.3下化骨龙F722飞控到底能不能启用气压计呢？
> > 
> > 
> > 可以用的
> 
> 我试了在4.2下用 set baro_bustype = SPI set baro_spi_device = 1 可以正常启用气压计
> 
> 但是在4.3下，只要一输入set baro_bustype = SPI 保存之后飞控重启就死机了，是不是和4.3对SPI总线定义有冲突？

You can try to enter:
“
set baro_i2c_device = 0
set baro_bustype =SPI
set baro_spi_device = 1
save
”
