### ISSUE TITLE
Add manufacturer id for DAKEFPV

### ISSUE THREAD

**Issue by ThanYangFPV** [betaflight/unified-targets#595]
Hi.
I want to apply for a manufacturer id for dakefpv. Here is our information.

Manufacturer name : DAKEFPV
Mail : sals@dakefpv.com
Website : [https://dakefpv.com/](https://dakefpv.com/)
ID : DAKE

If the application gets approved, I want to be his maintainer.
Thanks

**Comment by Asizon** [comment]
@ThanYangFPV  where is your pull request for hardware to maintain? Fast look in the website and seems that the Fcs comes from betafpv.

**Comment by ThanYangFPV** [comment]
> @ThanYangFPV where is your pull request for hardware to maintain? Fast look in the website and seems that the Fcs comes from betafpv.

Yes.We are proxying their product, this is temporary, once we have an ID, we will pull request belonging to our target, and then start making our product.

**Comment by Dakefpv** [comment]
@Asizon Hi，Asizon，Nice to meet you! I am Jason from DAKEFPV，I authorize thanyangfpv to maintain our flight control hardware!
