### ISSUE TITLE
Helio RC Spring IMU-F 

### ISSUE THREAD

**Issue by nightflasher** [betaflight/unified-targets#668]
## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem:
MISSING target for the Helio RC Sping IMU-F 
2. Include ways to reproduce the problem:
Looking in the repo, no helio target found
3. Provide as much information as possible about your hardware and software, including:
The Helio Spring flight controllers are still out there and needs to be addressed by betaflight - emuflight seems to have it working
4. Remove this Text :). NO! :-P

**Comment by sugaarK** [comment]
No it doesn’t need to be addressed by bf… time to move on and let these monstrosities die….
