### ISSUE TITLE
DarwinFPV SX1280 board lacks OSD

### ISSUE THREAD

**Issue by howels** [betaflight/unified-targets#773]
@DMAXYANG the DarwinFPV AIO SPI based eLRS boards seem to be using the target https://github.com/betaflight/unified-targets/blob/master/configs/default/DAFP-DARWINF4SX1280HD.config which lacks OSD support.
Understand that there may exist a board without OSD chip, but DarwinFPV sell SX1280 boards with OSD and these are lacking support currently.
Should we add `#define USE_MAX7456` to DARWINF4SX1280HD or create a new target for OSD-enabled versions of the board?

**Comment by haslinghuis** [comment]
Adding OSD driver will fix it.

**Comment by howels** [comment]
> Adding OSD driver will fix it.

Yes, but target is specifically named after the HD variant so the target name could confuse pilots
