### ISSUE TITLE
Manufacturer ID for HIFIONRC 

### ISSUE THREAD

**Issue by atgfpeyv** [betaflight/unified-targets#81]
As per https://github.com/betaflight/betaflight/blob/master/docs/TargetMaintenance/CreatingAUnifiedTarget.md, please assign manufacturer ID for HIFIONRC.

Requested Id : HIFI
Name : HIFIONRC
URL : (under construction, meet soon...If the construction is completed, I will add it up.)

A target definition of HIFIONRC will follow soon.

**Comment by mikeller** [comment]
Please update this when the URL is available, a manufacturer id will be assigned then.

**Comment by atgfpeyv** [comment]
@mikeller Thank you for your reminder, but our website is still under construciton. This is a domain name: http://www.hifionrc.com/. It should be open now. We are taking the time to perfect it.

**Comment by mikeller** [comment]
The website still looks a bit funny for a website offering RC related gear:

![image](https://user-images.githubusercontent.com/4742747/67628305-c9d6f900-f8c7-11e9-94a4-d0457770d8ac.png)

**Comment by atgfpeyv** [comment]
@mikeller Yeah. The website is still under construction.
