### ISSUE TITLE
Problem on DarwinFPV with BF 4.4

### ISSUE THREAD

**Issue by Denethor85** [betaflight/unified-targets#832]
### Describe the bug

With the DarwinFPV Baby Ape Pro drone, if you flash BF 4.4 RC4 with the target recommended by the parent company MATEKF411 the gyroscope no longer works, if instead you flash with the DARWINF411 target there are errors and problems in the default configuration at example the programmable LED doesn't work and I don't know if anything else

### To Reproduce

Flash BF 4.4 RC4 on Baby Ape

### Expected behavior

The Gyro working on MATEKF411 or everything works fine on DATWINF411

### Flight controller

Darwinfpv 15A 1-3S F411 Ultralight/Whoop AIO

**Comment by FulvioSpelta** [comment]
Hi all, I've just flashed the 4.4 using the configurator and the gyroscope is now not detected.
How's the state of this issue ? Is there a workaround ?

Thanks a lot.

**Comment by haslinghuis** [comment]
> here is the PR to fix this issue https://github.com/betaflight/unified-targets/pull/918

**Comment by haslinghuis** [comment]
Please use DARWINF411 target instead.

You might have to change in CLI:

    set gyro_1_sensor_align = CW180
    set gyro_1_align_pitch = 0
    set gyro_1_align_yaw = 0
    save

**Comment by FulvioSpelta** [comment]
OK, I've already flashed the controller using the DARWINF411 target that is automatically detected by the configurator.
Regardings the defauls I've deselected GPS that isn't present and then flashed.

Later (sorry I've not here with me the drone) I'll apply the sets you just suggested and i'll provide e feedback.
