### ISSUE TITLE
DarwinFPV wrong or missing gyro (ICM20689) 

### ISSUE THREAD

**Issue by nightflasher** [betaflight/unified-targets#834]
After I've seen the issue on betaflight, mentioning the new DarwinF411 target, I had a look at it and the gyro is MPU6000 only. But the boards I have (three) all use the ICM20689, which I think was correctly configured with the MatekF411.

**Comment by haslinghuis** [comment]
Please flash the build with  `USE_GYRO_ICM20689 USE_ACC_ICM20689` in custom defines with `DARWINF411` target and report back.

**Comment by nightflasher** [comment]
Tried and is working. Thx!

Btw: where can I find the documentation for the custom defines?

**Comment by haslinghuis** [comment]
[betaflight.com](https://betaflight.com/docs/configurator/firmware-flasher-tab#custom-defines)
