### ISSUE TITLE
HAKRC F722D gyroscope not working in betaflight 4.4.0 

### ISSUE THREAD

**Issue by PaxHitech88** [betaflight/unified-targets#839]
### Describe the bug

I loaded betaflight 4.4.0 with the betaflight configurator 10.9.0 RC5 in my HAKRC F722D board but the accelerometer and gyroscope are not recognized, while in the stable version they work correctly.

![image](https://user-images.githubusercontent.com/93522833/215068787-e8684f17-8ee6-491e-9234-d74a61fb5bc3.png)

![image](https://user-images.githubusercontent.com/93522833/215068950-75fda5dd-bd34-4e41-9fa0-6b4001584fe8.png)

### To Reproduce

load the firmware in dfu mode with betaflight configurator 10.9 RC5

### Expected behavior

Accelerometer and gyroscope should work properly, giving me the possibility to calibrate them.

### Configurator version

10.9 RC5

### Flight controller configuration

```txt
# 

# diff

# version
# Betaflight / STM32F7X2 (S7X2) 4.4.0 Jan 17 2023 / 03:19:58 (a7cf8f0c6) MSP API: 1.45

# config: YES

# start the command batch
batch start

board_name HAKRCF722D
manufacturer_id HARC

# master
set osd_canvas_width = 30
set osd_canvas_height = 13
set gyro_1_align_yaw = 1800
set gyro_2_align_yaw = 900

profile 0

rateprofile 0

# end the command batch
batch end

#
```

**Comment by haslinghuis** [comment]
@PaxHitech88 did you flash with Core Only enabled before submitting ID?

**Comment by PaxHitech88** [comment]
umhhh I don't remember🤔

**Comment by haslinghuis** [comment]
Then do it again otherwise we don't have all we need for investigation

**Comment by PaxHitech88** [comment]
> Then do it again otherwise we don't have all we need for investigation

Can you tell me how to do it so I can do it right away? I tried again today to load the new firmware 4.4.0 but it gives me the same problem.

**Comment by haslinghuis** [comment]
@PaxHitech88 

- Detect Board
- Enable Core Only
- Press Flash firmware 
- Press Submit Support Data button in CLI tab
- Report the ID here

**Comment by PaxHitech88** [comment]
ok the ID is
Id: "aaa914e7-7850-4ad2-9e5b-24750ac26e07"

**Comment by PaxHitech88** [comment]
i started configuring i in the configuration tab but i noticed that if i save and restart it doesn't save.
While if I load the diff file previously made and with which I flew this is loaded but with some errors.

**Comment by haslinghuis** [comment]
Thanks @PaxHitech88 when above PR is merged it will work out of the box.

For now you can flash with custom defines: `ACC_SPI_MPU6500 GYRO__SPI_MPU6500`

**Comment by PaxHitech88** [comment]
I try right away

**Comment by PaxHitech88** [comment]
I did as you told me but it didn't solve the problem.

![image](https://user-images.githubusercontent.com/93522833/215812098-0a487218-b120-4781-988a-af874d139fe6.png)

**Comment by KarateBrot** [comment]
@haslinghuis wrote:
> Thanks @PaxHitech88 when above PR is merged it will work out of the box.
>
> For now you can flash with custom defines: ACC_SPI_MPU6500 GYRO__SPI_MPU6500

There is a typo in the custom defines you mentioned (double underscore in `GYRO_SPI_MPU6500`). Can this be the culprit (from copy pasting it over from github to configurator)?

**Comment by haslinghuis** [comment]
Good spot and my bad - forgot the SPI part so added that without noticing double underscore.

**Comment by PaxHitech88** [comment]
I try and update you

**Comment by PaxHitech88** [comment]
> Is `Expert Mode` enabled in firmware flasher tab?
> Only visible after enabling show releases candidates

yes I had the export mode active

**Comment by PaxHitech88** [comment]
I just tried it and so it works or at least it recognizes it. I'll try to configure everything and update you. 
Thank you very much for helping.
