### ISSUE TITLE
problem about betaflight 4.4 and betaflight 4.3 F411SX1280

### ISSUE THREAD

**Issue by EmaxModel** [betaflight/unified-targets#899]
betafligt 4.3 can't suport comman like ???
resource RX_SPI_EXPRESSLRS_RESET 1 B09
resource RX_SPI_EXPRESSLRS_BUSY 1 A13
my firmware can't work on betaflight 4.3. Reciver can't detect and the rx led do not flash.

**Comment by KarateBrot** [comment]
BF 4.3 works only with **SPI ELRS v2** and BF 4.4 only works with **SPI ELRS v3**.
When using SPI receivers, make sure to use ELRS v2 on BF 4.3 and ELRS v3 on BF 4.4. Maybe this is part of your problem?

**Comment by EmaxModel** [comment]
I got it,thanks
