### ISSUE TITLE
No barometer BMP280 for FLYWOOF411 via BF4.4 Cloud Build Config

### ISSUE THREAD

**Issue by mxfre** [betaflight/unified-targets#958]
1. Barometer BMP280 cannot be enabled on NOXE V1 (deluxe version) Flight Controller, target FLYWOOF411, via BF4.4 Cloud Build Config.
Previously in BF4.1 it can be enabled in config and cli.

https://www.amazon.ae/Upgraded-20x20mm-Controller-Barometer-Blackbox/dp/B087X7KRZR

2. To Reproduce

Update NOXE V1 flight controller to BF4.4 (Firmware Target: FLYWOOF411) via BF Configurator 10.9.
Enable "Barometer" in BF Configurator 10.9.

Expected behavior

On Board Blackbox shall be available in the BF Configurator 10.9 - Blackbox tab option.

Baro works in "CORE only", but I need GPS.

I have tried Cloud Build Mode adding "BARO_BMP280" in the custom defines field, but still Baro are not available/detected.
I think the problem in the Cloud Build is due to the Unified Target for FLYWOOF411 was not updated with:

#Define USE_BARO_BMP280 

https://github.com/betaflight/unified-targets/blob/master/configs/default/FLWO-FLYWOOF411.config

**Comment by haslinghuis** [comment]
To use custom defines please enable show release candidates and then enable expert mode.
If `BARO_BMP280` still does not work also try `BARO BARO_BMP280`

**Comment by mxfre** [comment]
It's the same, BARO is not recognized.
As I said, I think the problem in the Cloud Build is due to the Unified Target for FLYWOOF411 was not updated with:

#Define USE_BARO_BMP280

https://github.com/betaflight/unified-targets/blob/master/configs/default/FLWO-FLYWOOF411.config

**Comment by haslinghuis** [comment]
The original FLYWOOF411 has no baro. Our policy is not to add drivers not used on the original target.

![image](https://user-images.githubusercontent.com/8344830/227032447-2a767a84-5cd1-4d7b-92e9-482a88a4e5e7.png)

Please share the support ID after flashing core build.

**Comment by mxfre** [comment]
FLYWOOF411 is not the same as FLYWOOF411 v2.1.
On my NOXE V1 (deluxe version), I flashed Betaflight 4.2.11 firmware for target FLYWOOF411.
BARO is available.
![baro_4 2 11](https://user-images.githubusercontent.com/57189501/228041400-e6b14b98-f1a3-4e6c-8936-16aba595dfe5.jpg)

![baro_4 2 11_2](https://user-images.githubusercontent.com/57189501/228041513-b933bc6e-b046-4d6b-9043-9d36a299b752.jpg)

[dump_Baro_4.2.11.txt](https://github.com/betaflight/unified-targets/files/11082145/dump_Baro_4.2.11.txt)

**Comment by mxfre** [comment]
I just noticed you added "#define USE_BARO_BMP280" to the Unified Target for FLYWOOF411.
Baro works now by adding "BARO BARO_BMP280" to custom defines.
Thank you.

**Comment by haslinghuis** [comment]
Fixed in #977
