### ISSUE TITLE
Custom config needed for a fc with different gyro alignment?

### ISSUE THREAD

**Issue by johnelliott** [betaflight/unified-targets#98]
I got a new FC from flight that took some custom config:

```# version
# Betaflight / STM32F7X2 (S7X2) 4.1.0 Oct 16 2019 / 11:58:45 (c37a7c91a) MSP API: 1.42
# manufacturer_id: EXUA   board_name: EXF722DUAL   custom defaults: YES
```

iFlight f7 twin-g for DJI air unit. Not the same as the other F7 twin-g stacks. 

When I tried to fly, it freaked out in a cyclical pattern each time because—as I found out via trial and error—one gyro was 90º off. I don't think the same custom defaults can apply for these two stacks (I have both).

<img width="801" alt="image" src="https://user-images.githubusercontent.com/5633265/67628445-c6962b80-f83b-11e9-9d2e-263b3d4a9389.png">

I think iFlight needs to add a custom config for the board with different sensor alignment. I could be totally wrong here. This is my first issue to unified configs.

**Comment by johnelliott** [comment]
@Linjieqiang perhaps you can help out here since Mike added you to as a maintainer :)

**Comment by Docteh** [comment]
Have you tried [IFF7_TWIN_G](https://github.com/betaflight/unified-targets/blob/master/configs/default/IFRC-IFF7_TWIN_G.config)?

https://github.com/betaflight/unified-targets/blob/f05568005adf44646588ace8dbabb75b7c6adbf1/configs/default/IFRC-IFF7_TWIN_G.config#L132-L136

**Comment by johnelliott** [comment]
I will double check, but the point I made above is that the same config does not work between the two boards.

**Comment by mikeller** [comment]
@johnelliott: From what you are stating above, this seems to be different hardware, and (at least) have a different gyro orientation. You could try to address this by manually setting the board orientation, but in the long run this should probably have a dedicated target provided by the manufacturer.

**Comment by johnelliott** [comment]
Thanks @mikeller, this is different hardware that's receiving incorrect custom config.

The screenshot posted above has the corrected configuration and the quad flies perfectly after determining what the sensor alignment actually is.

I can just make a PR for this, probably Friday night or this weekend once I have time to read docs. I haven't looked into how custom configs are mapped to boards but this must be a simple case.
