### ISSUE TITLE
DarwinFPV MATEKF411 Gyro not found

### ISSUE THREAD

**Issue by Daumaz** [betaflight/unified-targets#994]
Hello, today I flashed Betaflight 4.4.1 to my DarwinFPV Baby Ape V2 Pro and the gyro was not recognized. FC specifications say it should be MPU6500 or ICM20689(SPI).
Support data submitted, id: "f172538f-6f37-4c61-a0d5-50ae33a5f0ce"
Configurator: 10.9.0 (697943b)
Firmware: 4.4.1 BTFL
Target: MTKS/MATEKF411(STM32F411)

**Comment by haslinghuis** [comment]
@Daumaz you can try DARWINF411 instead.

**Comment by Daumaz** [comment]
Thanks for the tip, but I did a custom configuration. Just leaving information here.
